# Generated by Django 5.1.6 on 2025-05-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginadmin',
            name='department',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='loginadmin',
            name='year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='loginstudent',
            name='department',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='loginstudent',
            name='year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='loginteacher',
            name='department',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='loginteacher',
            name='year',
            field=models.IntegerField(default=2024),
        ),
    ]
