# Generated by Django 5.1.6 on 2025-05-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_loginadmin_department_loginadmin_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginadmin',
            name='year',
            field=models.CharField(default='2024', max_length=4),
        ),
        migrations.AlterField(
            model_name='loginstudent',
            name='year',
            field=models.CharField(default='2024', max_length=4),
        ),
        migrations.AlterField(
            model_name='loginteacher',
            name='year',
            field=models.CharField(default='2024', max_length=4),
        ),
    ]
