# Generated by Django 5.1.6 on 2025-07-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_alter_loginadmin_year_alter_loginstudent_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginadmin',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='loginadmin',
            name='semester',
            field=models.CharField(default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='loginstudent',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='loginstudent',
            name='semester',
            field=models.CharField(default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='loginteacher',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='loginteacher',
            name='semester',
            field=models.CharField(default='1', max_length=2),
        ),
    ]
