# Generated by Django 5.1.6 on 2025-07-15 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_loginadmin_email_loginadmin_semester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginadmin',
            name='email',
        ),
        migrations.RemoveField(
            model_name='loginadmin',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='loginstudent',
            name='email',
        ),
        migrations.RemoveField(
            model_name='loginstudent',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='loginteacher',
            name='email',
        ),
        migrations.RemoveField(
            model_name='loginteacher',
            name='semester',
        ),
    ]
