# Generated by Django 5.1.6 on 2025-07-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_remove_loginadmin_email_remove_loginadmin_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginadmin',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='loginstudent',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='loginteacher',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
    ]
