# Generated by Django 5.1.6 on 2025-08-05 11:32

import Account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_loginadmin_email_loginstudent_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginstudent',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=Account.models.unique_file_path),
        ),
    ]
